import * as spellCategories from './SpellCategories';
export default [

	{
		spellCategory: spellCategories.COMBAT,
		isElemental: true,
		isDirect: false,
		name: 'Acid Stream',
		isLOS: true,
		isArea: false,
		isMana: false,
		isPhysicalDamage: true,
		drain: -3,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: true,
		isDirect: false,
		name: 'Toxic Wave',
		isLOS: true,
		isArea: true,
		isMana: false,
		isPhysicalDamage: true,
		drain: -1,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: false,
		isDirect: false,
		name: 'Punch',
		isLOS: false,
		isArea: false,
		isMana: false,
		isPhysicalDamage: false,
		drain: -6,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: false,
		isDirect: false,
		name: 'Clout',
		isLOS: true,
		isArea: false,
		isMana: false,
		isPhysicalDamage: false,
		drain: -3,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: false,
		isDirect: false,
		name: 'Blast',
		isLOS: true,
		isArea: true,
		isMana: false,
		isPhysicalDamage: false,
		drain: 0,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: false,
		isDirect: true,
		name: 'DeathTouch',
		isLOS: false,
		isArea: false,
		isMana: true,
		isPhysicalDamage: true,
		drain: -6,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: false,
		isDirect: true,
		name: 'Manabolt',
		isLOS: true,
		isArea: false,
		isMana: true,
		isPhysicalDamage: true,
		drain: -3,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: false,
		isDirect: true,
		name: 'Manaball',
		isLOS: true,
		isArea: true,
		isMana: true,
		isPhysicalDamage: true,
		drain: 0,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: true,
		isDirect: false,
		name: 'Flamethrower',
		isLOS: true,
		isArea: false,
		isMana: false,
		isPhysicalDamage: true,
		drain: -3,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: true,
		isDirect: false,
		name: 'Fireball',
		isLOS: true,
		isArea: true,
		isMana: false,
		isPhysicalDamage: true,
		drain: -1,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: true,
		isDirect: false,
		name: 'Lightning Bolt',
		isLOS: true,
		isArea: false,
		isMana: false,
		isPhysicalDamage: true,
		drain: -3,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: true,
		isDirect: false,
		name: 'Ball Lightning',
		isLOS: true,
		isArea: true,
		isMana: false,
		isPhysicalDamage: true,
		drain: -1,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: false,
		isDirect: true,
		name: 'Shatter',
		isLOS: false,
		isArea: false,
		isMana: false,
		isPhysicalDamage: true,
		drain: -6,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: false,
		isDirect: true,
		name: 'Powerbolt',
		isLOS: true,
		isArea: false,
		isMana: false,
		isPhysicalDamage: true,
		drain: -3,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: false,
		isDirect: true,
		name: 'Powerball',
		isLOS: true,
		isArea: true,
		isMana: false,
		isPhysicalDamage: true,
		drain: 0,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: false,
		isDirect: true,
		name: 'Knockout',
		isLOS: false,
		isArea: false,
		isMana: true,
		isPhysicalDamage: false,
		drain: -6,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: false,
		isDirect: true,
		name: 'Stunbolt',
		isLOS: true,
		isArea: false,
		isMana: true,
		isPhysicalDamage: false,
		drain: -3,
		duration: 'I'
	},
	{
		spellCategory: spellCategories.COMBAT,
		isElemental: false,
		isDirect: true,
		name: 'Stunball',
		isLOS: true,
		isArea: true,
		isMana: true,
		isPhysicalDamage: false,
		drain: 0,
		duration: 'I'
	},

	{
		spellCategory: spellCategories.DETECTION,
		name: 'Analyze Device',
		isActive: true,
		isDirectional: true,
		isMana: false,
		isLOS: false,
		isArea: false,
		isExtendedArea: false,
		isPsychic: false,
		duration: 'S',
		drain: -3
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Analyze Magic',
		isActive: true,
		isDirectional: true,
		isMana: false,
		isLOS: false,
		isArea: false,
		isExtendedArea: false,
		isPsychic: false,
		duration: 'S',
		drain: -3
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Analyze Truth',
		isActive: true,
		isDirectional: true,
		isMana: true,
		isLOS: false,
		isArea: false,
		isExtendedArea: false,
		isPsychic: false,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Clairaudience',
		isActive: false,
		isDirectional: true,
		isMana: true,
		isLOS: false,
		isArea: false,
		isExtendedArea: false,
		isPsychic: false,
		duration: 'S',
		drain: -3
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Clairvoyance',
		isActive: false,
		isDirectional: true,
		isMana: true,
		isLOS: false,
		isArea: false,
		isExtendedArea: false,
		isPsychic: false,
		duration: 'S',
		drain: -3
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Combat Sense',
		isActive: true,
		isDirectional: false,
		isMana: true,
		isLOS: false,
		isArea: false,
		isExtendedArea: false,
		isPsychic: true,
		duration: 'S',
		drain: 0
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Detect Enemies',
		isActive: true,
		isDirectional: false,
		isMana: true,
		isLOS: false,
		isArea: true,
		isExtendedArea: false,
		isPsychic: false,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Detect Enemies, Extended',
		isActive: true,
		isDirectional: false,
		isMana: true,
		isLOS: false,
		isArea: false,
		isExtendedArea: true,
		isPsychic: false,
		duration: 'S',
		drain: 0
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Detect Individual',
		isActive: true,
		isDirectional: false,
		isMana: true,
		isLOS: false,
		isArea: true,
		isExtendedArea: false,
		isPsychic: false,
		duration: 'S',
		drain: -3
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Detect Life',
		isActive: true,
		isDirectional: false,
		isMana: true,
		isLOS: false,
		isArea: false,
		isExtendedArea: true,
		isPsychic: false,
		duration: 'S',
		drain: -1
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Detect [Life Form]',
		isActive: true,
		isDirectional: false,
		isMana: true,
		isLOS: false,
		isArea: true,
		isExtendedArea: false,
		isPsychic: false,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Detect [Life Form], Extended',
		isActive: true,
		isDirectional: false,
		isMana: true,
		isLOS: false,
		isArea: false,
		isExtendedArea: true,
		isPsychic: false,
		duration: 'S',
		drain: 0
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Detect Magic',
		isActive: true,
		isDirectional: false,
		isMana: true,
		isLOS: false,
		isArea: true,
		isExtendedArea: false,
		isPsychic: false,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Detect Magic, Extended',
		isActive: true,
		isDirectional: false,
		isMana: true,
		isLOS: false,
		isArea: true,
		isExtendedArea: false,
		isPsychic: false,
		duration: 'S',
		drain: 0
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Detect [Object]',
		isActive: true,
		isDirectional: false,
		isMana: false,
		isLOS: false,
		isArea: true,
		isExtendedArea: false,
		isPsychic: false,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Mindlink',
		isActive: true,
		isDirectional: false,
		isMana: true,
		isLOS: false,
		isArea: false,
		isExtendedArea: false,
		isPsychic: true,
		duration: 'S',
		drain: -1
	},
	{
		spellCategory: spellCategories.DETECTION,
		name: 'Mind Probe',
		isActive: true,
		isDirectional: true,
		isMana: true,
		isLOS: false,
		isArea: false,
		isExtendedArea: false,
		isPsychic: false,
		duration: 'S',
		drain: 0
	},
	{
		spellCategory: spellCategories.HEALTH,
		name: 'Antidote',
		isEssence: false,
		isMana: true,
		isLOS: false,
		isArea: false,
		duration: 'P',
		drain: -3
	},
	{
		spellCategory: spellCategories.HEALTH,
		name: 'Cure Disease',
		isEssence: true,
		isMana: true,
		isLOS: false,
		isArea: false,
		duration: 'P',
		drain: -4
	},
	{
		spellCategory: spellCategories.HEALTH,
		name: 'Decrease [Attribute]',
		isEssence: true,
		isMana: false,
		isLOS: false,
		isArea: false,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.HEALTH,
		name: 'Detox',
		isEssence: false,
		isMana: true,
		isLOS: false,
		isArea: false,
		duration: 'P',
		drain: -6
	},
	{
		spellCategory: spellCategories.HEALTH,
		name: 'Heal',
		isEssence: true,
		isMana: true,
		isLOS: false,
		isArea: false,
		duration: 'P',
		drain: -4
	},
	{
		spellCategory: spellCategories.HEALTH,
		name: 'Increase [Attribute]',
		isEssence: true,
		isMana: false,
		isLOS: false,
		isArea: false,
		duration: 'S',
		drain: -3
	},
	{
		spellCategory: spellCategories.HEALTH,
		name: 'Increase Reflexes',
		isEssence: true,
		isMana: false,
		isLOS: false,
		isArea: false,
		duration: 'S',
		drain: 0
	},
	{
		spellCategory: spellCategories.HEALTH,
		name: 'Oxygenate',
		isEssence: false,
		isMana: false,
		isLOS: false,
		isArea: false,
		duration: 'S',
		drain: -5
	},
	{
		spellCategory: spellCategories.HEALTH,
		name: 'Prophylaxis',
		isEssence: false,
		isMana: true,
		isLOS: false,
		isArea: false,
		duration: 'S',
		drain: -4
	},
	{
		spellCategory: spellCategories.HEALTH,
		name: 'Resist Pain',
		isEssence: false,
		isMana: true,
		isLOS: false,
		isArea: false,
		duration: 'P',
		drain: -6
	},
	{
		spellCategory: spellCategories.HEALTH,
		name: 'Stabilize',
		isEssence: false,
		isMana: true,
		isLOS: false,
		isArea: false,
		duration: 'P',
		drain: -4
	},

	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Agony',
		isRealistic: true,
		isMultisense: false,
		isLOS: true,
		isArea: false,
		isMana: true,
		duration: 'S',
		drain: -4
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Mass Agony',
		isRealistic: true,
		isMultisense: true,
		isLOS: true,
		isArea: true,
		isMana: true,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Bugs',
		isRealistic: true,
		isMultisense: true,
		isLOS: true,
		isArea: false,
		isMana: true,
		duration: 'S',
		drain: -3
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Swarm',
		isRealistic: true,
		isMultisense: true,
		isLOS: true,
		isArea: true,
		isMana: true,
		duration: 'S',
		drain: -1
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Confusion',
		isRealistic: true,
		isMultisense: true,
		isLOS: true,
		isArea: false,
		isMana: true,
		duration: 'S',
		drain: -3
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Mass Confusion',
		isRealistic: true,
		isMultisense: true,
		isLOS: true,
		isArea: true,
		isMana: true,
		duration: 'S',
		drain: -1
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Chaos',
		isRealistic: true,
		isMultisense: true,
		isLOS: true,
		isArea: false,
		isMana: false,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Chaotic World',
		isRealistic: true,
		isMultisense: true,
		isLOS: true,
		isArea: true,
		isMana: false,
		duration: 'S',
		drain: 0
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Entertainment',
		isRealistic: false,
		isMultisense: true,
		isLOS: true,
		isArea: true,
		isMana: true,
		duration: 'S',
		drain: -3
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Trid Entertainment',
		isRealistic: false,
		isMultisense: true,
		isLOS: true,
		isArea: true,
		isMana: false,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Invisibility',
		isRealistic: true,
		isMultisense: false,
		isLOS: true,
		isArea: false,
		isMana: true,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Improved Invisibility',
		isRealistic: true,
		isMultisense: false,
		isLOS: true,
		isArea: false,
		isMana: false,
		duration: 'S',
		drain: -1
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Mask',
		isRealistic: true,
		isMultisense: true,
		isLOS: false,
		isArea: false,
		isMana: true,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Physical Mask',
		isRealistic: true,
		isMultisense: true,
		isLOS: false,
		isArea: false,
		isMana: false,
		duration: 'S',
		drain: -1
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Phantasm',
		isRealistic: true,
		isMultisense: true,
		isLOS: true,
		isArea: true,
		isMana: true,
		duration: 'S',
		drain: -1
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Trid Phantasm',
		isRealistic: true,
		isMultisense: true,
		isLOS: true,
		isArea: true,
		isMana: false,
		duration: 'S',
		drain: 0
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Hush',
		isRealistic: true,
		isMultisense: false,
		isLOS: true,
		isArea: true,
		isMana: true,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Silence',
		isRealistic: true,
		isMultisense: false,
		isLOS: true,
		isArea: true,
		isMana: false,
		duration: 'S',
		drain: -1
	},
	{
		spellCategory: spellCategories.ILLUSION,
		name: 'Stealth',
		isRealistic: true,
		isMultisense: false,
		isLOS: true,
		isArea: false,
		isMana: false,
		duration: 'S',
		drain: -2
	},

	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Armor',
		isPhysical: true,
		isMental: false,
		isEnvironmental: false,
		isDamaging: false,
		isLOS: true,
		isArea: false,
		isMana: false,
		duration: 'S',
		drain: -1
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Control Actions',
		isPhysical: false,
		isMental: true,
		isEnvironmental: false,
		isDamaging: false,
		isLOS: true,
		isArea: false,
		isMana: true,
		duration: 'S',
		drain: -1
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Mob Control',
		isPhysical: false,
		isMental: true,
		isEnvironmental: false,
		isDamaging: false,
		isLOS: true,
		isArea: true,
		isMana: true,
		duration: 'S',
		drain: 1
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Control Thoughts',
		isPhysical: false,
		isMental: true,
		isEnvironmental: false,
		isDamaging: false,
		isLOS: true,
		isArea: false,
		isMana: true,
		duration: 'S',
		drain: 1
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Mob Mind',
		isPhysical: false,
		isMental: true,
		isEnvironmental: false,
		isDamaging: false,
		isLOS: true,
		isArea: true,
		isMana: true,
		duration: 'S',
		drain: 1
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'fling',
		isPhysical: true,
		isMental: false,
		isEnvironmental: false,
		isDamaging: false,
		isLOS: true,
		isArea: false,
		isMana: false,
		duration: 'I',
		drain: -2
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Ice Sheet',
		isPhysical: false,
		isMental: false,
		isEnvironmental: true,
		isLOS: true,
		isArea: true,
		isMana: false,
		duration: 'I',
		drain: 0
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Ignite',
		isPhysical: true,
		isMental: false,
		isEnvironmental: false,
		isLOS: true,
		isArea: false,
		isMana: false,
		duration: 'P',
		drain: -1
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Influence',
		isPhysical: false,
		isMental: true,
		isEnvironmental: false,
		isLOS: true,
		isArea: false,
		isMana: true,
		duration: 'P',
		drain: -1
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Levitate',
		isPhysical: true,
		isMental: false,
		isEnvironmental: false,
		isLOS: true,
		isArea: false,
		isMana: false,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Light',
		isPhysical: false,
		isMental: false,
		isEnvironmental: true,
		isLOS: true,
		isArea: true,
		isMana: false,
		duration: 'S',
		drain: -4
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Magic Fingers',
		isPhysical: true,
		isMental: false,
		isEnvironmental: false,
		isLOS: true,
		isArea: false,
		isMana: false,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Mana Barrier',
		isPhysical: false,
		isMental: false,
		isEnvironmental: true,
		isLOS: true,
		isArea: true,
		isMana: true,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Physical Barrier',
		isPhysical: false,
		isMental: false,
		isEnvironmental: true,
		isLOS: true,
		isArea: true,
		isMana: false,
		duration: 'S',
		drain: -1
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Poltergeist',
		isPhysical: false,
		isMental: false,
		isEnvironmental: true,
		isLOS: true,
		isArea: true,
		isMana: false,
		duration: 'S',
		drain: -2
	},
	{
		spellCategory: spellCategories.MANIPULATION,
		name: 'Shadow',
		isPhysical: false,
		isMental: false,
		isEnvironmental: true,
		isLOS: true,
		isArea: true,
		isMana: false,
		duration: 'S',
		drain: -3
	}
];

